version: "3.2"

services:
  msa:
    build: ./msa
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - DS_HOST=msb:6000
    ports:
      - 80:5000
  msb:
    build: ./msb
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=6000
